@startuml ShowContextMenu

participant User
participant MenuDog
participant MenuFactory
participant PathProvider
participant IconProvider
participant RegistryEditor

User -> MenuDog: Launch
activate MenuDog

User -> MenuDog: Specify object path
MenuDog -> MenuFactory: getMenu
activate MenuFactory

MenuFactory -> PathProvider: getPIDL
activate PathProvider
PathProvider -> MenuFactory: returns an\narray of PIDL

MenuFactory -> MenuFactory: createMenu\nref: CreatePopupMenu
MenuFactory -> IconProvider: getIcon
activate IconProvider
IconProvider -> MenuFactory: returns the handle of required icon

MenuFactory -> MenuDog: returns the\nhandle of menu
MenuDog -> MenuDog: displayMenu
MenuDog -> User: Ready

User -> MenuDog: Select reserved menu
MenuDog -> MenuDog: Interactivity:\ncheckboxes, ...

User -> MenuDog: Commit
MenuDog -> RegistryEditor: Action
activate RegistryEditor

RegistryEditor -> RegistryEditor: editContextMenu
RegistryEditor -> MenuDog: returns the result
MenuDog -> User: result

@enduml
