@startuml ShowContextMenu

participant User
participant UI
participant MenuFactory
participant PathProvider
participant IconProvider
participant RegistryEditor

User -> UI: Launch
activate UI

User -> UI: Specify object path
UI -> MenuFactory: getMenu
activate MenuFactory

MenuFactory -> PathProvider: getPIDL
activate PathProvider
PathProvider -> MenuFactory: returns an\narray of PIDL

MenuFactory -> MenuFactory: createMenu\nref: CreatePopupMenu
MenuFactory -> IconProvider: getIcon
activate IconProvider
IconProvider -> MenuFactory: returns the handle of required icon

MenuFactory -> UI: returns the\nhandle of menu
UI -> UI: displayMenu
UI -> User: Ready

User -> UI: Select reserved menu
UI -> UI: Interactivity:\ncheckboxes, ...

User -> UI: Commit
UI -> RegistryEditor: Action
activate RegistryEditor

RegistryEditor -> RegistryEditor: editContextMenu
RegistryEditor -> UI: returns the result
UI -> User: result

@enduml
